# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skeema < Formula
  desc "Skeema is a tool for managing MySQL tables and schema changes in a declarative fashion using pure SQL."
  homepage "https://www.skeema.io/"
  version "1.10.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_mac_arm64.tar.gz"
      sha256 "d18bafe441dc9ee7d4a3fb9a82343b4cfa6176f23d71df0263a23e64c31a5f9c"

      def install
        bin.install "skeema"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_mac_amd64.tar.gz"
      sha256 "442823a5758062a220620186c812ef73b61e9d35072179f2fee4ef770399d6a7"

      def install
        bin.install "skeema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_linux_arm64.tar.gz"
      sha256 "f72cf930142c38a4f5a8e0a714ea9a010aba6c2f78ce07aafb694833c0eebb06"

      def install
        bin.install "skeema"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_linux_amd64.tar.gz"
      sha256 "6ef6321dc11ee1ecf0824c21df9b29a6f2254cd379384187f866070c0e29a0af"

      def install
        bin.install "skeema"
      end
    end
  end
end
