# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skeema < Formula
  desc "Skeema is a tool for managing MySQL tables and schema changes in a declarative fashion using pure SQL."
  homepage "https://www.skeema.io/"
  version "1.10.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_mac_arm64.tar.gz"
      sha256 "d878545b89dd237d5a415ac606382e5f9efebf36bfadf90cc26c68b5cd563069"

      def install
        bin.install "skeema"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_mac_amd64.tar.gz"
      sha256 "7adf63488afeb17e256f2c05a55c114d374af9be4dfc7e72565e05a3ba6dc356"

      def install
        bin.install "skeema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_linux_arm64.tar.gz"
      sha256 "fb9ee0d3d318242d4dc94b8538d07f5c84ebb6132b6e6a90c21951347ce5d79d"

      def install
        bin.install "skeema"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dashhudson/skeema/releases/download/v1.10.0/skeema_1.10.0_linux_amd64.tar.gz"
      sha256 "4b89c2f1dbd67003bf702486f5e20d4f3c3e9907cc064a523abc054dbe9fd920"

      def install
        bin.install "skeema"
      end
    end
  end
end
